language: android
jdk:
  - oraclejdk8

before_install:
  # Gradle
  - wget http://services.gradle.org/distributions/gradle-2.6-bin.zip
  - unzip gradle-2.6-bin.zip
  - export GRADLE_HOME=$PWD/gradle-2.6
  - export PATH=$GRADLE_HOME/bin:$PATH

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22

script:
  gradle check

notifications:
  email: false
